# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.101:1521/xe
#    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: eco_fresh
    password: eco1505!

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml