CREATE TABLE ECO_FRESH.EMPLOYEE_JJY_MST
(
	  EMPLOYEE_NO VARCHAR2(9) NOT NULL
	, EMPLOYEE_NM VARCHAR2(30) NOT NULL
	, HP_NO VARCHAR2(11)
	, EMAIL VARCHAR2(50)
	, ENTR_DT VARCHAR2(8) NOT NULL
	, RETR_DT VARCHAR2(8)
	, WRK_TYP_CD VARCHAR2(2)
	, DEL_YN VARCHAR2(1) DEFAULT 'N' NOT NULL
	, REG_ID VARCHAR2(30) NOT NULL
	, REG_DTM VARCHAR2(14) NOT NULL
	, MOD_ID VARCHAR2(30) NOT NULL
	, MOD_DTM VARCHAR2(14) NOT NULL
	, BASE_ADR VARCHAR2(100)
	, DTL_ADR VARCHAR2(100)
	, ZIP_NO VARCHAR2(5)
	, BIRTH_DT VARCHAR2(8)
);

ALTER TABLE ECO_FRESH.EMPLOYEE_JJY_MST ADD PSTN_NM VARCHAR2(10);
ALTER TABLE ECO_FRESH.EMPLOYEE_JJY_MST ADD RANK_NM VARCHAR2(10) DEFAULT '주임' NOT NULL;

COMMENT ON TABLE ECO_FRESH.EMPLOYEE_JJY_MST IS '직원 관리';

COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.EMPLOYEE_NO IS '직원번호';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.EMPLOYEE_NM IS '직원이름';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.HP_NO IS '핸드폰 번호';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.EMAIL IS '이메일';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.ENTR_DT IS '입사일자';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.RETR_DT IS '퇴사일자';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.WRK_TYP_CD IS '근무형태코드';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.DEL_YN IS '삭제여부';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.REG_ID IS '등록자';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.REG_DTM IS '등록일시';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.MOD_ID IS '수정자';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.MOD_DTM IS '수정일시';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.BASE_ADR IS '기본주소';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.DTL_ADR IS '상세주소';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.ZIP_NO IS '우편번호';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.BIRTH_DT IS '생년월일';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.PSTN_NM IS '직책이름';
COMMENT ON COLUMN ECO_FRESH.EMPLOYEE_JJY_MST.RANK_NM IS '직급이름';

CREATE UNIQUE INDEX ECO_FRESH.PK_EMPLOYEE_JJY_MST ON ECO_FRESH.EMPLOYEE_JJY_MST(EMPLOYEE_NO);

ALTER TABLE ECO_FRESH.EMPLOYEE_JJY_MST
ADD CONSTRAINT PK_EMPLOYEE_JJY_MST PRIMARY KEY (EMPLOYEE_NO)
USING INDEX ECO_FRESH.PK_EMPLOYEE_JJY_MST ENABLE;

--테스트 데이터--
INSERT INTO ECO_FRESH.EMPLOYEE_JJY_MST (
			  EMPLOYEE_NO 
			, EMPLOYEE_NM 
			, HP_NO 
			, EMAIL 
			, ENTR_DT 
			, RETR_DT 
			, WRK_TYP_CD
			, DEL_YN 
			, REG_ID 
			, REG_DTM 
			, MOD_ID
			, MOD_DTM 
			, BASE_ADR 
			, DTL_ADR 
			, ZIP_NO 
			, BIRTH_DT
			, PSTN_NM
			, RANK_NM 
			)
	VALUES (
			  'E20240001'
			, '오라클테스트'
			, '01012345678'
			, 'example@ecosystems.co.kr'
			, '20240201'
			, ''
			, 'Y'
			, 'N'
			, '오라클테스트'
			, '20240202'
			, '오라클테스트'
			, '20240202'
			, '경기도 과천시 과천대로7길'
			, '33, 디테크타워 1505'
			, '00000'
			, '19991231'
			, ''
			, '주임'
	);
	
INSERT INTO ECO_FRESH.EMPLOYEE_JJY_MST (
			  EMPLOYEE_NO 
			, EMPLOYEE_NM 
			, HP_NO 
			, EMAIL 
			, ENTR_DT 
			, RETR_DT 
			, WRK_TYP_CD
			, DEL_YN 
			, REG_ID 
			, REG_DTM 
			, MOD_ID
			, MOD_DTM 
			, BASE_ADR 
			, DTL_ADR 
			, ZIP_NO 
			, BIRTH_DT
			, PSTN_NM
			, RANK_NM 
			)
	VALUES (
			  'E20240002'
			, '오라클테스트1'
			, '01012345678'
			, 'example1@ecosystems.co.kr'
			, '20240201'
			, ''
			, 'Y'
			, 'N'
			, '오라클테스트1'
			, '20240202'
			, '오라클테스트1'
			, '20240202'
			, '경기도 과천시 과천대로7길'
			, '33, 디테크타워 1505'
			, '00000'
			, '19991231'
			, ''
			, '주임'
	);

ALTER TABLE EMPLOYEE_JJY_MST MODIFY PSTN_NM VARCHAR2(30);
ALTER TABLE EMPLOYEE_JJY_MST MODIFY RANK_NM VARCHAR2(30);